name: dividido
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  flutter_riverpod: ^2.5.1
  easy_localization: ^3.0.7
  uuid: ^4.5.1
  cloud_firestore: ^5.4.4
  flutter_dotenv: ^5.2.1
  firebase_storage: ^12.3.4
  cloud_functions: ^5.1.3
  firebase_app_check: ^0.3.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - .env
